### ISSUE TITLE
[CRASH] Game fails to start when installed with EnhancedVisuals

### ISSUE THREAD

**Issue by DeshiDesu** [SettingDust/dawncraft-fixes#5]
**Logs**
[2023-05-31-2.log.gz](https://github.com/SettingDust/dawncraft-fixes/files/11608692/2023-05-31-2.log.gz)
```
[00:44:35] [main/INFO]: ModLauncher running: args [--username, DeshiDesu, --version, 1.18.2, --gameDir, C:\Users\dafat\AppData\Roaming\ATLauncher\instances\Debugging, --assetsDir, C:\Users\dafat\AppData\Roaming\ATLauncher\assets, --assetIndex, 1.18, --uuid, 5339f81ae68a4589bec84bc9c087a79a, --accessToken, ????????, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 40.2.2, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914, --width=854, --height=480]
[00:44:35] [main/INFO]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.1 by Microsoft
[00:44:36] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/dafat/AppData/Roaming/ATLauncher/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=CLIENT
[00:44:36] [main/INFO]: Found mod file CreativeCore_FORGE_v2.6.16_mc1.18.2.jar of type MOD with provider {mods folder locator at C:\Users\dafat\AppData\Roaming\ATLauncher\instances\Debugging\mods}
[00:44:36] [main/INFO]: Found mod file dawncraft-fixes-0.8.2.jar of type MOD with provider {mods folder locator at C:\Users\dafat\AppData\Roaming\ATLauncher\instances\Debugging\mods}
[00:44:36] [main/INFO]: Found mod file EnhancedVisuals_FORGE_v1.6.4_mc1.18.2.jar of type MOD with provider {mods folder locator at C:\Users\dafat\AppData\Roaming\ATLauncher\instances\Debugging\mods}
[00:44:36] [main/WARN]: Mod file C:\Users\dafat\AppData\Roaming\ATLauncher\libraries\net\minecraftforge\fmlcore\1.18.2-40.2.2\fmlcore-1.18.2-40.2.2.jar is missing mods.toml file
[00:44:36] [main/WARN]: Mod file C:\Users\dafat\AppData\Roaming\ATLauncher\libraries\net\minecraftforge\javafmllanguage\1.18.2-40.2.2\javafmllanguage-1.18.2-40.2.2.jar is missing mods.toml file
[00:44:36] [main/WARN]: Mod file C:\Users\dafat\AppData\Roaming\ATLauncher\libraries\net\minecraftforge\lowcodelanguage\1.18.2-40.2.2\lowcodelanguage-1.18.2-40.2.2.jar is missing mods.toml file
[00:44:36] [main/WARN]: Mod file C:\Users\dafat\AppData\Roaming\ATLauncher\libraries\net\minecraftforge\mclanguage\1.18.2-40.2.2\mclanguage-1.18.2-40.2.2.jar is missing mods.toml file
[00:44:36] [main/INFO]: Found mod file fmlcore-1.18.2-40.2.2.jar of type LIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@a68df9
[00:44:36] [main/INFO]: Found mod file javafmllanguage-1.18.2-40.2.2.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@a68df9
[00:44:36] [main/INFO]: Found mod file lowcodelanguage-1.18.2-40.2.2.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@a68df9
[00:44:36] [main/INFO]: Found mod file mclanguage-1.18.2-40.2.2.jar of type LANGPROVIDER with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@a68df9
[00:44:36] [main/INFO]: Found mod file client-1.18.2-20220404.173914-srg.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@a68df9
[00:44:36] [main/INFO]: Found mod file forge-1.18.2-40.2.2-universal.jar of type MOD with provider net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@a68df9
[00:44:36] [main/INFO]: Found 2 dependencies adding them to mods collection
[00:44:36] [main/INFO]: Found mod file mixinextras-forge-0.2.0-beta.7.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@37c5fc56
[00:44:36] [main/INFO]: Found mod file MixinExtras-0.2.0-beta.7.jar of type GAMELIBRARY with provider net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator@37c5fc56
[00:44:37] [main/INFO]: Compatibility level set to JAVA_17
[00:44:37] [main/INFO]: Launching target 'forgeclient' with arguments [--version, 1.18.2, --gameDir, C:\Users\dafat\AppData\Roaming\ATLauncher\instances\Debugging, --assetsDir, C:\Users\dafat\AppData\Roaming\ATLauncher\assets, --uuid, 5339f81ae68a4589bec84bc9c087a79a, --username, DeshiDesu, --assetIndex, 1.18, --accessToken, ????????, --userType, msa, --versionType, release, --width=854, --height=480]
[00:44:37] [main/WARN]: Reference map 'creativecore.mixins.refmap.json' for creativecore.mixins.json could not be read. If this is a development environment you can ignore this message
[00:44:37] [main/WARN]: Error loading class: bottomtextdanny/braincell/mod/capability/BCCapabilityHelper (java.lang.ClassNotFoundException: bottomtextdanny.braincell.mod.capability.BCCapabilityHelper)
[00:44:37] [main/WARN]: @Mixin target bottomtextdanny.braincell.mod.capability.BCCapabilityHelper was not found dawncraft-fixes.mixins.json:braincell.MixinBCCapabilityHelper
[00:44:37] [main/WARN]: Error loading class: bottomtextdanny/braincell/mod/hooks/BCMovementHooks (java.lang.ClassNotFoundException: bottomtextdanny.braincell.mod.hooks.BCMovementHooks)
[00:44:37] [main/WARN]: @Mixin target bottomtextdanny.braincell.mod.hooks.BCMovementHooks was not found dawncraft-fixes.mixins.json:braincell.MixinBCMovementHooks
[00:44:37] [main/WARN]: Error loading class: bottomtextdanny/dannys_expansion/content/structures/klifour_spawn/KlifourSpawnPiece (java.lang.ClassNotFoundException: bottomtextdanny.dannys_expansion.content.structures.klifour_spawn.KlifourSpawnPiece)
[00:44:37] [main/WARN]: @Mixin target bottomtextdanny.dannys_expansion.content.structures.klifour_spawn.KlifourSpawnPiece was not found dawncraft-fixes.mixins.json:dannysexpansion.InvokerKlifourSpawnPiece
[00:44:37] [main/WARN]: Error loading class: bottomtextdanny/dannys_expansion/tables/DEStructures (java.lang.ClassNotFoundException: bottomtextdanny.dannys_expansion.tables.DEStructures)
[00:44:37] [main/WARN]: @Mixin target bottomtextdanny.dannys_expansion.tables.DEStructures was not found dawncraft-fixes.mixins.json:dannysexpansion.MixinDEStructures
[00:44:37] [main/WARN]: Error loading class: bottomtextdanny/dannys_expansion/content/structures/klifour_spawn/KlifourSpawnPiece (java.lang.ClassNotFoundException: bottomtextdanny.dannys_expansion.content.structures.klifour_spawn.KlifourSpawnPiece)
[00:44:37] [main/WARN]: @Mixin target bottomtextdanny.dannys_expansion.content.structures.klifour_spawn.KlifourSpawnPiece was not found dawncraft-fixes.mixins.json:dannysexpansion.MixinKlifourSpawnPiece
[00:44:37] [main/WARN]: Error loading class: bottomtextdanny/dannys_expansion/_base/capabilities/player/PlayerHelper (java.lang.ClassNotFoundException: bottomtextdanny.dannys_expansion._base.capabilities.player.PlayerHelper)
[00:44:37] [main/WARN]: @Mixin target bottomtextdanny.dannys_expansion._base.capabilities.player.PlayerHelper was not found dawncraft-fixes.mixins.json:dannysexpansion.MixinPlayerHelper
[00:44:37] [main/WARN]: Error loading class: reascer/efdg/gameasset/EFAnimations (java.lang.ClassNotFoundException: reascer.efdg.gameasset.EFAnimations)
[00:44:37] [main/WARN]: @Mixin target reascer.efdg.gameasset.EFAnimations was not found dawncraft-fixes.mixins.json:dualgreatsword.MixinEFAnimations
[00:44:37] [main/WARN]: Error loading class: reascer/efdg/world/capabilities/item/EFWeaponCapabilityPresets (java.lang.ClassNotFoundException: reascer.efdg.world.capabilities.item.EFWeaponCapabilityPresets)
[00:44:37] [main/WARN]: @Mixin target reascer.efdg.world.capabilities.item.EFWeaponCapabilityPresets was not found dawncraft-fixes.mixins.json:dualgreatsword.MixinEFWeaponCapabilityPresets
[00:44:37] [main/WARN]: Error loading class: superlord/goblinsanddungeons/common/util/GDArmorMaterial (java.lang.ClassNotFoundException: superlord.goblinsanddungeons.common.util.GDArmorMaterial)
[00:44:37] [main/WARN]: @Mixin target superlord.goblinsanddungeons.common.util.GDArmorMaterial was not found dawncraft-fixes.mixins.json:goblinsanddungeons.MixinGDArmorMaterial
[00:44:37] [main/WARN]: Error loading class: com/craisinlord/integrated_api/misc/maptrades/StructureSpecificMaps$TreasureMapForEmeralds (java.lang.ClassNotFoundException: com.craisinlord.integrated_api.misc.maptrades.StructureSpecificMaps$TreasureMapForEmeralds)
[00:44:37] [main/WARN]: @Mixin target com.craisinlord.integrated_api.misc.maptrades.StructureSpecificMaps$TreasureMapForEmeralds was not found dawncraft-fixes.mixins.json:integrated_api.MixinStructureSpecificMaps
[00:44:37] [main/WARN]: Error loading class: com/feywild/quest_giver/EventListener (java.lang.ClassNotFoundException: com.feywild.quest_giver.EventListener)
[00:44:37] [main/WARN]: @Mixin target com.feywild.quest_giver.EventListener was not found dawncraft-fixes.mixins.json:questgiver.MixinEventListener
[00:44:37] [main/WARN]: Error loading class: untamedwilds/util/EntityDataHolder (java.lang.ClassNotFoundException: untamedwilds.util.EntityDataHolder)
[00:44:37] [main/WARN]: @Mixin target untamedwilds.util.EntityDataHolder was not found dawncraft-fixes.mixins.json:untamedwilds.MixinEntityDataHolder
[00:44:37] [main/WARN]: Error loading class: untamedwilds/util/EntityUtils (java.lang.ClassNotFoundException: untamedwilds.util.EntityUtils)
[00:44:37] [main/WARN]: @Mixin target untamedwilds.util.EntityUtils was not found dawncraft-fixes.mixins.json:untamedwilds.MixinEntityUtils
[00:44:37] [main/WARN]: Error loading class: untamedwilds/block/NestReptileBlock (java.lang.ClassNotFoundException: untamedwilds.block.NestReptileBlock)
[00:44:37] [main/WARN]: @Mixin target untamedwilds.block.NestReptileBlock was not found dawncraft-fixes.mixins.json:untamedwilds.MixinNestReptileBlock
[00:44:37] [main/WARN]: Error loading class: com/cursedcauldron/unvotedandshelved/events/MobEvents (java.lang.ClassNotFoundException: com.cursedcauldron.unvotedandshelved.events.MobEvents)
[00:44:37] [main/WARN]: @Mixin target com.cursedcauldron.unvotedandshelved.events.MobEvents was not found dawncraft-fixes.mixins.json:unvoted.MixinMobEvents
[00:44:37] [main/WARN]: Error loading class: tschipp/callablehorses/client/gui/GuiStatViewer (java.lang.ClassNotFoundException: tschipp.callablehorses.client.gui.GuiStatViewer)
[00:44:37] [main/WARN]: @Mixin target tschipp.callablehorses.client.gui.GuiStatViewer was not found dawncraft-fixes.mixins.json:callablehorses.MixinGuiStatViewer
[00:44:37] [main/WARN]: Error loading class: yesman/epicfight/client/events/engine/RenderEngine$Events (java.lang.ClassNotFoundException: yesman.epicfight.client.events.engine.RenderEngine$Events)
[00:44:37] [main/WARN]: @Mixin target yesman.epicfight.client.events.engine.RenderEngine$Events was not found dawncraft-fixes.mixins.json:epicfight.MixingRenderEngineEvents
[00:44:37] [main/FATAL]: Mixin prepare failed preparing EntityAccessor in enhancedvisuals.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException Critical problem: enhancedvisuals.mixins.json:EntityAccessor target net.minecraft.world.entity.Entity was loaded too early.
org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: enhancedvisuals.mixins.json:EntityAccessor target net.minecraft.world.entity.Entity was loaded too early.
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:947) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:881) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:850) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:775) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:539) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-9.1.3.jar:9.1.3+9.1.3+main.9b69c82a]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:632) ~[?:?]
	at java.lang.Class.forName(Class.java:545) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.2.2.jar%2317!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]

```

**Mods**
>Version: MC 1.18.2
Modloader: Forge 40.2.4
EnhancedVisuals_FORGE_v1.6.4_mc1.18.2.jar
CreativeCore_FORGE_v2.6.16_mc1.18.2.jar
dawncraft-fixes-0.8.2.jar

**These two errors are shown in console**
>[31/05/2023 00:44:37 a.m.] Exception in thread "main" org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [enhancedvisuals.mixins.json:EntityAccessor] from phase [DEFAULT] in config [enhancedvisuals.mixins.json] FAILED during PREPARE
[31/05/2023 00:44:37 a.m.] Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: enhancedvisuals.mixins.json:EntityAccessor target net.minecraft.world.entity.Entity was loaded too early.

**Comment by SettingDust** [comment]
The log isn't match the issue. You should reproduce with only the three mods and provide the log

**Comment by DeshiDesu** [comment]
That log was before I tested with only those three mods sorry
[2023-05-31-1.log.gz](https://github.com/SettingDust/dawncraft-fixes/files/11608824/2023-05-31-1.log.gz)

**Comment by CreativeMD** [comment]
To be honest I have no idea what causes this kind of error.

**Comment by DeshiDesu** [comment]
It seems other people also had this issue and it had somehow(?) been resolved: https://github.com/SpongePowered/Mixin/issues/388
Im hoping this too would somehow resolve but in the meantime, I will be downgrading some mods.

**Comment by SettingDust** [comment]
Can you reproduce with this? @DeshiDesu 
[dawncraft-fixes-0.8.2.zip](https://github.com/SettingDust/dawncraft-fixes/files/11615089/dawncraft-fixes-0.8.2.zip)

**Comment by DeshiDesu** [comment]
> Can you reproduce with this? @DeshiDesu [dawncraft-fixes-0.8.2.zip](https://github.com/SettingDust/dawncraft-fixes/files/11615089/dawncraft-fixes-0.8.2.zip)

It worked without any crashes! I will give you the log soon

**Comment by DeshiDesu** [comment]
@SettingDust The file works thank you

**Comment by SettingDust** [comment]
As the https://github.com/SpongePowered/Mixin/issues/388 point out. I shouldn't call the logger from main class. Will publish a new version

**Comment by DeshiDesu** [comment]
Glad it helped 🙂
